// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jctpxfouwuhrkcqcshzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjdHB4Zm91d3VocmtjcWNzaHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxMTAxNDgsImV4cCI6MjA4MTY4NjE0OH0.B7G1nnthZI2lMfUrwri9jgehda4eEIds_KbxUTKocXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);